[nats]
host = "127.0.0.1"
port = 4222
[nats.consumer]
subjects = []
delivery_subject = "rtgb.controller.consumer"
name = "controller-consumer"

[nats.cert]
absolute_folder_path = ""
key_file_name = ""
cert_file_name = ""
root_ca_file_name = ""


[postgres]
database = "rtgb_scheduler"
username = "service_rtgb_scheduler"
host = "127.0.0.1"
port = 5432

[postgres.cert]
absolute_folder_path = ""
key_file_name = ""
cert_file_name = ""
root_ca_file_name = ""
