[nats.client]
host = "127.0.0.1"
port = 4222
creds_path = "/home/antoine/.local/share/nats/nsc/keys/creds/operator/account/user.creds"

[nats.client.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.crt"

[nats.consumer]
subjects = ["a-suject", "another"]
delivery_subject = "delivery-subject"
name = "consumer-name"

[nats.publisher]
command_topic_template = "shellies/<model>-<deviceid>/relay/0/command"


[postgres]
database = "db_name"
username = "user_name"
host = "127.0.0.1"
port = 5432

[postgres.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.crt"
