[nats]

host = "127.0.0.1"
port = 4222
[nats.consumer]
subjects = ["a-suject", "another"]
name = "consumer-name"

[nats.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.cert"


[postgres]
name = "db-name"
host = "127.0.0.0"
port = 5432

[postgres.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.cert"
