[nats]
host = "127.0.0.1"
port = 4222

[nats.consumer]
subjects = ["a-suject", "another"]
delivery_subject = "delivery-subject"
name = "consumer-name"

[nats.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.crt"

[postgres]
database = "db_name"
username = "user_name"
host = "127.0.0.1"
port = 5432
tables = ["table_name"]

[postgres.cert]
absolute_folder_path = "/home/certs"
key_file_name = "client.key"
cert_file_name = "client.crt"
root_ca_file_name = "ca.crt"
